version: '3'

services:
  hacg:
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017
    container_name: hacg
    build:
      context: .
    image: "hacg:0.0.1"
    restart: always
